FROM nangohq/nango-server:hosted

ENV NANGO_DB_MIGRATION_FOLDER=/usr/nango-server/src/packages/database/lib/migrations
ENV NANGO_ENCRYPTION_KEY=${NANGO_ENCRYPTION_KEY}
ENV NANGO_DB_USER=${NANGO_DB_USER}
ENV NANGO_DB_PASSWORD=${NANGO_DB_PASSWORD}
ENV NANGO_DB_HOST=${NANGO_DB_HOST}
ENV NANGO_DB_NAME=${NANGO_DB_NAME}
ENV NANGO_DB_SSL=${NANGO_DB_SSL}
ENV NANGO_DB_ADDITIONAL_SCHEMAS=${NANGO_DB_ADDITIONAL_SCHEMAS}
ENV NANGO_DB_POOL_MIN=${NANGO_DB_POOL_MIN}
ENV NANGO_DB_POOL_MAX=${NANGO_DB_POOL_MAX}
ENV RECORDS_DATABASE_URL=${RECORDS_DATABASE_URL:-postgresql://nango:nango@nango-db:5432/nango}
ENV SERVER_PORT=${SERVER_PORT}
ENV NANGO_SERVER_URL=${NANGO_SERVER_URL:-http://localhost:3003}
ENV NANGO_DASHBOARD_USERNAME=${NANGO_DASHBOARD_USERNAME}
ENV NANGO_DASHBOARD_PASSWORD=${NANGO_DASHBOARD_PASSWORD}
ENV LOG_LEVEL=${LOG_LEVEL:-info}
ENV TELEMETRY=${TELEMETRY}
ENV NANGO_SERVER_WEBSOCKETS_PATH=${NANGO_SERVER_WEBSOCKETS_PATH}
ENV NANGO_LOGS_ENABLED=${NANGO_LOGS_ENABLED:-false}
ENV NANGO_LOGS_ES_URL=${NANGO_LOGS_ES_URL:-http://nango-elasticsearch:9200}
ENV NANGO_LOGS_ES_USER=${NANGO_LOGS_ES_USER}
ENV NANGO_LOGS_ES_PWD=${NANGO_LOGS_ES_PWD}

COPY ./packages/shared/providers.yaml /usr/nango-server/src/packages/shared/providers.yaml

EXPOSE ${PORT:-3003}
WORKDIR /usr/nango-server/src

# CMD [ "npm", "start" ]
CMD [ "node", "packages/server/dist/server.js" ]
